#spring:
#    data:
#        elasticsearch:
#            cluster-name: nini
#            cluster-nodes: 127.0.0.1:9300
#            local: false
#            repositories:
#                enable: true